### ISSUE TITLE
Unable to fetch data

### ISSUE THREAD

**Issue by jjj5313** [bencorrado/pmsensor#5]
Hi. i am new to home assistant. i have been trying using pms5003 in my setup. However, home assistant unable to fetch data from sensor.

it is like:
2017-05-20 13:56:36 ERROR (Thread-9) [homeassistant.components.sensor.serial_pm] Could not read PM10 value
2017-05-20 13:56:38 ERROR (Thread-4) [pmsensor.serial_pm] read timeout after 2 seconds, read 0 bytes
2017-05-20 13:56:38 ERROR (Thread-4) [homeassistant.components.sensor.serial_pm] Could not read PM1 value
2017-05-20 13:56:40 ERROR (Thread-1) [pmsensor.serial_pm] read timeout after 2 seconds, read 0 bytes

Is there anything wrong with the code?  Thanks

**Comment by open-homeautomation** [comment]
This simply means that the code can't read data from your sensor. Try to connect directly via a serial terminal and check if you get data back.

**Comment by ronakdedhia18** [comment]
> Hi. i am new to home assistant. i have been trying using pms5003 in my setup. However, home assistant unable to fetch data from sensor.
> 
> it is like:
> 2017-05-20 13:56:36 ERROR (Thread-9) [homeassistant.components.sensor.serial_pm] Could not read PM10 value
> 2017-05-20 13:56:38 ERROR (Thread-4) [pmsensor.serial_pm] read timeout after 2 seconds, read 0 bytes
> 2017-05-20 13:56:38 ERROR (Thread-4) [homeassistant.components.sensor.serial_pm] Could not read PM1 value
> 2017-05-20 13:56:40 ERROR (Thread-1) [pmsensor.serial_pm] read timeout after 2 seconds, read 0 bytes
> 
> Is there anything wrong with the code? Thanks

Can you please tell what is the unit for the values we are getting?

Date_Time | PM1 | PM2.5 | PM10
-- | -- | -- | --
2019/02/14 09:52:35 | 260 | 2854 | 3936

I am getting this kind of output

Thankyou.

**Comment by bencorrado** [comment]
The units are μg/m³
