### ISSUE TITLE
Problem with outliers

### ISSUE THREAD

**Issue by linuxlurak** [bencorrado/pmsensor#6]
Hi
I'm not sure if this is an issue...

In Home Assistant I get such results for PM25:
![image](https://user-images.githubusercontent.com/3813355/28283709-dc0fa140-6b2e-11e7-83dc-abd6a3c87c10.png)
No idea why. 

PM10 looks ok:
![image](https://user-images.githubusercontent.com/3813355/28283768-173fc966-6b2f-11e7-9f68-553bd95f6ef6.png)

Is there any chance to rule out outliers? Is this a bug? I'll restart HASS and report back if the problem persists or not.

Thanks for your great work anyways! Cheers!

**Comment by linuxlurak** [comment]
I dumped the data from the home assistant database:
Go to sqlite cli:
`sqlite3 /home/pi/.homeassistant/home-assistant_v2.db`
then enter:
```
.mode csv 
.headers on 
.out pm10 
select * FROM states WHERE entity_id="sensor.pm10";
.out pm25 
select * FROM states WHERE entity_id="sensor.pm25";
```
this are samples of pm25 pm10 that are next to each other:

> state_id,domain,entity_id,state,attributes,event_id,last_changed,last_updated,created
> 2817330,sensor,sensor.pm25,4932.2,"{""unit_of_measurement"": ""\u00b5g/m\u00b3"", ""friendly_name"": ""PM2.5""}",,"2017-07-18 18:01:05.519336","2017-07-18 18:01:05.519336","2017-07-18 18:01:06.803446"
> 2
> 
> state_id,domain,entity_id,state,attributes,event_id,last_changed,last_updated,created
> 2817332,sensor,sensor.pm10,3.0,"{""unit_of_measurement"": ""\u00b5g/m\u00b3"", ""friendly_name"": ""PM10""}",,"2017-07-18 18:01:06.165309","2017-07-18 18:01:06.165309","2017-07-18 18:01:07.198581"
> 2

**Comment by bencorrado** [comment]
@linuxlurak Did you ever resolve this issue?
